# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SimpleApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Storage'
pod 'Firebase/Database'
pod 'Firebase/Firestore'
pod 'Kingfisher'
pod 'SideMenu'
  # Pods for SimpleApp

# add the Firebase pod for Google Analytics
pod 'Firebase/Analytics'
# add pods for any other desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods
  target 'SimpleAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SimpleAppUITests' do
    # Pods for testing
  end

end
